import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header
          style={{
            background: "pink",
            margin: "8px",
            padding: "5px",
            textAlign: "center",
            fontWeight: "bold",
            fontSize: "28px",
          }}
        >
          <h1 style={{ fontSize: "28px", fontWeight: "bold" }}>
            Products Store
          </h1>
          <nav style={{ marginTop: "8px", fontSize: "18px" }}>
            <Link href="/" style={{ marginRight: "15px" }}>
              Home
            </Link>
            <Link href="/products">Products</Link>
          </nav>
        </header>
        {children}
        <footer
          style={{
            background: "gray",
            margin: "8px",
            padding: "5px",
            textAlign: "center",
          }}
        >
          <h3>© 2026 Products Store </h3>
          <p>Built with Next.js</p>
        </footer>
      </body>
    </html>
  );
}
