import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header
          style={{
            background: "pink",
            margin: "8px",
            padding: "5px",
            textAlign: "center",
            fontWeight: "bold",
            fontSize: "28px",
          }}
        >
          Products Store
        </header>
        {children}
        <footer
          style={{
            background: "gray",
            margin: "8px",
            padding: "5px",
            textAlign: "center",
          }}
        >
          <h3>© 2026 Products Store </h3>
          <p>Built with Next.js</p>
        </footer>
      </body>
    </html>
  );
}
